services:
  rust-app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rust-app.entrypoints=https"
      - "traefik.http.routers.rust-app.tls=true"
      - "traefik.http.routers.rust-app.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.rust-app.loadbalancer.server.port=${PORT}"
    networks:
      - proxy
      - internal
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/dbname

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    expose:
      - 5432

networks:
  proxy:
    external: true
  internal:
    internal: true

volumes:
  postgres_data:
