services:
  rust-app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rust-app.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.rust-app.loadbalancer.server.port=${PORT}"
